# Data structure/World

In [5]:
from src.board import Board
import numpy as np

In [6]:
board = Board()

In [7]:
board.valid()

True

In [8]:
board._world[0] = np.arange(1, 10)
board._world[:,0] = np.array([1, 4, 5, 2, 3, 6, 7, 8, 9])

In [9]:
board.valid()

True

In [10]:
board = Board()
board._world[0] = np.arange(1, 10)
board._world[:,0] = np.arange(1, 10)
board._world[-1, -1] = 9
board.valid()

False

In [11]:
board = Board()
board._world[0] = np.arange(1, 10)
board._world[:,0] = np.arange(1, 10)
board._world[-1, -1] = 9
print(board.valid())

False


In [12]:
board = Board()
board._world[0] = np.arange(1, 10)
board._world[:,0] = np.arange(1, 10)
board._world[-1, 0] = 1
print(board.valid())

False


In [13]:
board = Board()
board._world[0] = np.arange(1, 10)
board._world[:,0] = np.arange(1, 10)
# board._world[1, 1] = 1
print(board)
print(board.valid())

[[1 2 3 4 5 6 7 8 9]
 [2 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0]
 [6 0 0 0 0 0 0 0 0]
 [7 0 0 0 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0]
 [9 0 0 0 0 0 0 0 0]]
False


In [14]:
print(board)

[[1 2 3 4 5 6 7 8 9]
 [2 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0]
 [4 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0]
 [6 0 0 0 0 0 0 0 0]
 [7 0 0 0 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0]
 [9 0 0 0 0 0 0 0 0]]


In [15]:
board = Board()
board._world[0] = np.arange(1, 10)
board._world[:,0] = np.array([1, 4, 5, 2, 3, 6, 7, 8, 9])
board.set(5, 3, 3)
print(board)
board.valid()

[[1 2 3 4 5 6 7 8 9]
 [4 0 0 0 0 0 0 0 0]
 [5 0 0 0 0 0 0 0 0]
 [2 0 0 5 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0]
 [6 0 0 0 0 0 0 0 0]
 [7 0 0 0 0 0 0 0 0]
 [8 0 0 0 0 0 0 0 0]
 [9 0 0 0 0 0 0 0 0]]


True

In [16]:
from src.board import Board

In [17]:
board = Board()

In [18]:
board

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]

In [19]:
board.set(1, 0, 0)

True

In [20]:
board.set(1, 1, 0)

False